### ISSUE TITLE
路由拦截方式

### ISSUE THREAD

**Issue by nei1ee** [uni-helper/vite-plugin-uni-middleware#2]
### Clear and concise description of the problem

或许可以重写跳转来实现更好的拦截

### Suggested solution

[uni-app 怎么实现路由拦截](https://juejin.cn/post/7119274924149047327)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by KeJunMao** [comment]
好主意

**Comment by KeJunMao** [comment]
现在的声明周期法确实差点意思

**Comment by KeJunMao** [comment]
不过重写跳转解决不了直接通过 url 进入的问题，以及微信小程序端点击 tabbar

**Comment by nei1ee** [comment]
还要支持 `Vue2` 吗？

**Comment by KeJunMao** [comment]
当然不支持了

**Comment by nei1ee** [comment]
看到一个不错的https://gitee.com/gowiny/uni-router
